---
version: '3.4'
volumes:
  fedora_test:
  db_test:
  es_test:
  goaws_test:
  ldap_test:
  minio_test:
  solr_test:
services:
  iiif:
    depends_on:
    - minio
    image: nulib/iiif-express
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      target: /tmp
    - type: volume
      target: /var/run
    ports:
    - 8184:3000
    environment:
    - TIFF_BUCKET=dev-pyramids
    - S3_ENDPOINT=http://minio:9000/
    - AWS_ACCESS_KEY_ID=minio
    - AWS_SECRET_ACCESS_KEY=minio123
    healthcheck:
      test:
      - CMD
      - wget
      - "--quiet"
      - "--tries=1"
      - "--spider"
      - http://localhost:3000/iiif/2/
      interval: 30s
      timeout: 5s
      retries: 3
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      source: db_test
      target: /data
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    environment:
    - PGDATA=/data
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=d0ck3r
    ports:
    - 5434:5432
    command: postgres -c max_connections=300
    healthcheck:
      test: "CMD echo 'SELECT 1' | PGPASSWORD=d0ck3r psql --host 127.0.0.1 --username docker
  --dbname docker --quiet --no-align --tuples-only"
      interval: 30s
      timeout: 5s
      retries: 3
  elasticproxy:
    depends_on:
    - elasticsearch
    image: nulib/elasticproxy:latest
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      target: /home/node
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    ports:
    - 3335:3334
    environment:
      UPSTREAM: http://elasticsearch:9200/
      API_TOKEN_HEADER: X-Api-Token
      API_TOKEN_SECRET: ab00ffc725da64fa07b20f42ed8bbcf0fda5779aa55c90cedf3a81e09e3a2b14
      OPENAM_SERVER: https://websso.it.northwestern.edu/amserver/
      OPENAM_COOKIE: openAMssoToken
    healthcheck:
      test:
      - CMD
      - wget
      - "--quiet"
      - "--tries=1"
      - "--spider"
      - http://localhost:3334/auth/whoami
      interval: 30s
      timeout: 5s
      retries: 3
  elasticsearch:
    image: bitnami/elasticsearch:6.8.14
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      source: es_test
      target: /bitnami/elasticsearch/data
    - type: volume
      target: /tmp
    - type: volume
      target: /opt/bitnami/elasticsearch
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    - ./extras/elasticsearch/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
    ports:
    - 9202:9200
    environment:
      ELASTICSEARCH_HEAP_SIZE: "256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
      - CMD
      - curl
      - "-f"
      - http://localhost:9200/
      interval: 30s
      timeout: 5s
      retries: 3
  fedora:
    image: samvera/fcrepo4:4.7.5
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      source: fedora_test
      target: /data
    - type: volume
      target: /tmp
    - type: volume
      target: /var/lib/jetty
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    ports:
    - 8986:8080
  goaws:
    image: nulib/goaws
    restart: unless-stopped
    ports:
    - 4102:4100
    volumes:
    - goaws_test:/data
    healthcheck:
      test:
      - CMD
      - wget
      - -O
      - "-"
      - http://localhost:4100/?Action=ListQueues
      interval: 30s
      timeout: 5s
      retries: 3
    command: --persist /data/goaws.yaml
  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    restart: unless-stopped
    ports:
    - 5603:5601
    healthcheck:
      test:
      - CMD
      - curl
      - "-f"
      - http://localhost:5601/
      interval: 30s
      timeout: 5s
      retries: 3
  sqs:
    image: s12v/elasticmq
    restart: unless-stopped
    ports:
      - 9326:9324
  ldap:
    image: nulib/ldap-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: ldap_test
        target: /var/lib/samba
    ports:
      - 391:389
      - 638:636
    environment:
      DOMAIN: library.northwestern.edu
      DOMAINPASS: d0ck3rAdm1n!
      INSECURELDAP: "true"
      NOCOMPLEXITY: "true"
    healthcheck:
      test:
      - CMD
      - echo
      - ""
      - "|"
      - nc
      - localhost
      - "389"
      interval: 30s
      timeout: 5s
      retries: 3
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      source: minio_test
      target: /data
    - type: volume
      target: /root/.minio
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test:
      - CMD
      - wget
      - "--quiet"
      - "--tries=1"
      - "--spider"
      - http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 5s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
    - 5052:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: devstack
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
    - $HOME/.pgadmin:/var/lib/pgadmin
    - $HOME/.ssh:/root/.ssh
    - ./extras/pgadmin4/servers.json:/pgadmin4/servers.json
    - ./extras/pgadmin4/pgpass:/pgpass
  redis:
    image: redis:alpine
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    ports:
    - 6381:6379
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 30s
      timeout: 5s
      retries: 3
  solr:
    image: solr:7.2-alpine
    restart: unless-stopped
    read_only: true
    volumes:
    - type: volume
      source: solr_test
      target: /opt/solr/server/solr
    - type: volume
      target: /opt/solr/server
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    ports:
    - 8985:8983
    - 9985:9983
    command: solr -f -cloud
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
  transfer:
    image: nulib/devstack-transfer
    restart: unless-stopped
    read_only: true
    volumes:
      - fedora_test:/volumes/fedora
      - db_test:/volumes/db
      - minio_test:/volumes/minio
      - solr_test:/volumes/solr
      - es_test:/volumes/es
